global using DinkToPdf;
global using DinkToPdf.Contracts;
global using NeedAnalysisApp.Client.Repositories.Interfaces;
global using NeedAnalysisApp.Shared.Common;
global using NeedAnalysisApp.Shared.Dto;
global using Newtonsoft.Json;
global using System.Net.Http.Json;
global using System.Text;
global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Components.Authorization;
global using Microsoft.AspNetCore.SignalR.Client;
global using Microsoft.JSInterop;
global using NeedAnalysisApp.Shared;
global using NeedAnalysisApp.Shared.Dto.Chat;
global using System.Security.Claims;
global using static NeedAnalysisApp.Client.Pages.Chat.Panel;
global using Microsoft.AspNetCore.Components.Forms;